#!/usr/bin/env python3
"""Run Linear A analyses by subject; preserve the underlying calculations.

The numbered implementation files are kept unchanged for compatibility with
archived reports; later implementations carry descriptive names. This interface
provides descriptive output names and records exact input/output hashes. It is
an analysis runner, not a translator.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import platform
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / 'scripts'))
import phase4 as corpus

ANALYSES = {
    'accounting': ('phase4.py', {
        'phase4_summary.json': 'accounting_summary.json',
        'phase4_arithmetic.json': 'accounting_search.json',
        'phase4_morphology.json': 'candidate_forms.json',
        'phase4_reviewed_morphology.json': 'reviewed_candidate_forms.json',
    }),
    'endings': ('phase5.py', {
        'phase5_summary.json': 'endings_summary.json',
        'phase5_details.json': 'endings_details.json',
    }),
    'origin': ('phase5_anchor.py', {
        'phase5_anchor_results.json': 'origin_comparison.json',
    }),
    'headings': ('headings.py', {
        'heading_comparanda.json': 'heading_comparanda.json',
    }),
    'affixes': ('conditional_affix_controls.py', {
        'affix_controls.json': 'affix_controls.json',
    }),
    'fractions': ('fraction_accounting.py', {
        'fraction_accounting.json': 'fraction_accounting.json',
    }),
}
PERMUTATION_TOPICS = {'accounting', 'fractions'}
INPUTS = [
    'research.py', 'scripts/phase4.py', 'scripts/phase5.py',
    'scripts/phase5_anchor.py', 'scripts/headings.py', 'scripts/affix_controls.py',
    'scripts/fraction_accounting.py', 'scripts/conditional_affix_controls.py',
    'data/editorial_reviews.json',
    'data/phase5_reviews.json', 'data/phase5_semantic_anchors.json',
    'data/heading_comparanda.json',
]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run(topic: str, source: Path, output: Path, *, fetch: bool = False,
        permutations: int = 4999, seed: int = 20260914) -> dict:
    """Stage requested outputs and publish them only after all jobs succeed."""
    if topic not in {*ANALYSES, 'all'}:
        raise ValueError('Unknown analysis: ' + topic)
    if permutations < 0:
        raise ValueError('Permutations must be nonnegative')
    source, output = source.resolve(), output.resolve()
    if not source.exists():
        if not fetch:
            raise ValueError('Source missing: use --fetch or supply --source PATH')
        corpus.fetch_source(source)
    provenance = corpus.verify_source(source.read_bytes())
    topics = list(ANALYSES) if topic == 'all' else [topic]
    output.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='.linear-a-', dir=output) as temporary:
        stage = Path(temporary)
        pending = {}
        for name in topics:
            script, mapping = ANALYSES[name]
            command = [sys.executable, str(ROOT / 'scripts' / script),
                       '--source', str(source), '--output', str(stage)]
            if name in PERMUTATION_TOPICS:
                command += ['--permutations', str(permutations), '--seed', str(seed)]
            completed = subprocess.run(command, capture_output=True, text=True,
                                       encoding='utf-8', cwd=ROOT, check=False)
            if completed.returncode:
                detail = completed.stderr.strip() or completed.stdout[-2000:]
                raise RuntimeError(name + ' analysis failed: ' + detail)
            for old, new in mapping.items():
                path = stage / old
                # Validate output format before replacing any published result.
                json.loads(path.read_text(encoding='utf-8'))
                pending[new] = path
            log = stage / (name + '.log')
            log.write_text(completed.stdout + completed.stderr, encoding='utf-8')
            pending[name + '.log'] = log
        manifest = {
            'interface': 'topic-based analysis runner',
            'analysis': topic, 'python': platform.python_version(),
            'source': provenance,
            'parameters': {'permutations': permutations, 'seed': seed}
                          if PERMUTATION_TOPICS & set(topics) else {},
            'input_sha256': {name: sha256(ROOT / name) for name in INPUTS},
            'output_sha256': {name: sha256(path) for name, path in pending.items()
                              if name.endswith('.json')},
            'output_scope': 'Only files generated by this invocation are listed.',
            'interpretation': 'Computational reproduction does not validate translations.',
        }
        for name, path in pending.items():
            path.replace(output / name)
        corpus.write_json(output / 'run_manifest.json', manifest)
    return manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('analysis', choices=[*ANALYSES, 'all'])
    parser.add_argument('--fetch', action='store_true', help='Download missing pinned source')
    parser.add_argument('--source', type=Path, default=ROOT / 'data/LinearAInscriptions.js')
    parser.add_argument('--output', type=Path, default=ROOT / 'results/generated')
    parser.add_argument('--permutations', type=int, default=4999,
                        help='Accounting/fraction permutations; 0 omits permutation evidence')
    parser.add_argument('--seed', type=int, default=20260914,
                        help='Accounting/fraction random seed')
    args = parser.parse_args(argv)
    try:
        manifest = run(args.analysis, args.source, args.output, fetch=args.fetch,
                       permutations=args.permutations, seed=args.seed)
    except (OSError, ValueError, RuntimeError) as exc:
        print('ERROR: ' + str(exc), file=sys.stderr)
        return 1
    print('Wrote ' + ', '.join(manifest['output_sha256']) + '\nTo ' + str(args.output.resolve()))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
